version: "3.7"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: host
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_site:/srv
      - ./caddy/caddy_data:/data
      - ./caddy/caddy_config:/config
 
  vaultwarden:
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    image: vaultwarden/server:latest
    volumes:
      - ./vaultwarden/data:/data

  flatnotes:
    container_name: flatnotes
    image: dullage/flatnotes:latest
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - "./flatnotes/data:/data"
    ports:
      - "127.0.0.1:7777:8080"
    restart: unless-stopped

volumes:
  caddy_data:
    external: true
  caddy_config:
