version: "3.7"
services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    env_file: ../.env
    networks:
      - allinone
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/site:/srv
      - ./data/data:/data
      - ./data/config:/config
