version: "3.7"

services:
  vaultwarden:
    container_name: vaultwarden
    restart: unless-stopped
    networks:
      - allinone
    image: vaultwarden/server:latest
    volumes:
      - ./data:/data
